services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - flask-network


  flask-api:
    image: ghcr.io/ipshitachaudhuri/flask-api:v1.12

    container_name: flask-api

    ports:
      - "8000:8000"

    environment:
      DB_HOST: postgres-db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres-db

    networks:
      - flask-network


volumes:
  postgres-data:


networks:
  flask-network:

