services:

  flask-api:
    build: .
    container_name: flask-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
      DATABASE_HOST: postgres-db
      DATABASE_NAME: flaskdb
      DATABASE_USER: flaskuser
      DATABASE_PASSWORD: flaskpassword
    depends_on:
      - postgres-db


  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:

