apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"flask-api","namespace":"flask-app"},"spec":{"ports":[{"nodePort":30080,"port":8000,"targetPort":8000}],"selector":{"app":"flask-api"},"type":"NodePort"}}
  labels:
    app: flask-api
  name: flask-api
  namespace: flask-app
spec:
  clusterIP: 10.109.178.194
  clusterIPs:
    - 10.109.178.194
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 30080
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: flask-api
  sessionAffinity: None
  type: NodePort
