name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | \
          docker login --username AWS --password-stdin \
          024826530424.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t flask-api .

      - name: Tag Docker Image
        run: |
          docker tag flask-api:latest \
          024826530424.dkr.ecr.eu-central-1.amazonaws.com/flask-api:latest

      - name: Push Docker Image
        run: |
          docker push \
          024826530424.dkr.ecr.eu-central-1.amazonaws.com/flask-api:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull 024826530424.dkr.ecr.eu-central-1.amazonaws.com/flask-api:latest

            docker stop flask-api || true
            docker rm flask-api || true

            docker run -d \
              --restart unless-stopped \
              -p 8000:8000 \
              --name flask-api \
              024826530424.dkr.ecr.eu-central-1.amazonaws.com/flask-api:latest
