name: Build Push Deploy Flask API

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: 024826530424.dkr.ecr.eu-central-1.amazonaws.com/flask-api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | \
          docker login --username AWS --password-stdin \
          024826530424.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region eu-central-1 | \
            docker login --username AWS --password-stdin \
            024826530424.dkr.ecr.eu-central-1.amazonaws.com

            docker pull $IMAGE_NAME:${{ env.IMAGE_TAG }}

            docker stop flask-api || true
            docker rm flask-api || true

            docker run -d \
              --restart unless-stopped \
              -p 8000:8000 \
              --name flask-api \
              $IMAGE_NAME:${{ env.IMAGE_TAG }}

      - name: Health Check
        run: |
          sleep 10
          curl https://api.ipshitechnology.com/health
