name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flask-api .

      - name: Run Container
        run: |
          docker run -d -p 8000:8000 --name flask-test flask-api

      - name: Test API
        run: |
          sleep 5
          curl http://localhost:8000/health

      - name: Stop Container
        run: docker stop flask-test

